[book]
authors = ["Ondrej Janus"]
language = "cz"
multilingual = false
src = "src"
title = "O kostkách a lidech"

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = true
page-break = false
