version: 2.1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

executors:
  docker-executor:
    docker:
      - image: ubuntu:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y curl git unzip
      - checkout
      - run:
          name: Install mdbook from GitHub Releases
          command: |
            MDBOOK_VERSION=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
            curl -L -o mdbook.tar.gz "https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
            tar -xzf mdbook.tar.gz
            mv mdbook /usr/local/bin/mdbook
            chmod +x /usr/local/bin/mdbook
      - run:
          name: Version information
          command: mdbook -V
      - run:
          name: Build with mdbook
          command: mdbook build
      - persist_to_workspace:
          root: book
          paths:
            - .

  deploy:
    executor: docker-executor
    environment:
      TARGET_BRANCH: gh-pages
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y curl git unzip
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Git user
          command: sh ./.circleci/setup_user.sh $USER_EMAIL $USER_NAME
      - run:
          name: Prepare deployment
          command: |
            ls -al
            git clone --branch ${TARGET_BRANCH} --single-branch ${CIRCLE_REPOSITORY_URL} deploy
            cd deploy
            git rm -rf .
            cp -r ../book/* .
      - run:
          name: Deploy release
          command: sh ./.circleci/deploy.sh $TARGET_BRANCH $CIRCLE_SHA1
