version: 2.1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

executors:
  docker-executor:
    docker:
      - image: januson/mdbook-builder:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Build with mdbook
          command: mdbook build
      - run:
          name: Copy circleci config
          command: cp -r .circleci ./book
      - persist_to_workspace:
          root: book
          paths:
            - "*"
            - ".circleci/*"
            - ".nojekyll"

  deploy:
    executor: docker-executor
    environment:
      TARGET_BRANCH: gh-pages
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: Setup Git user
          command: sh ./.circleci/setup_user.sh $USER_EMAIL $USER_NAME
      - run:
          name: Prepare release branch
          command: sh ./.circleci/nuke_branch.sh $TARGET_BRANCH
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy release
          command: sh ./.circleci/deploy.sh $TARGET_BRANCH $CIRCLE_SHA1
