version: 2

jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/rust:latest
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: develop
      - TARGET_BRANCH: master
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install mdbook 
          command: cargo install mdbook
      - run:
          name: Build with mdbook
          command: mdbook build


