version: 2.1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

executors:
  docker-executor:
    docker:
      - image: rust:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install mdBook
          command: |
            cargo install mdbook
      - run:
          name: Build with mdbook
          command: mdbook build
      - persist_to_workspace:
          root: book
          paths:
            - .

  deploy:
    executor: docker-executor
    environment:
      TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Git user
          command: sh ./.circleci/setup_user.sh $USER_EMAIL $USER_NAME
      - run:
          name: Prepare deployment
          command: |
            ls -al
            git clone --branch ${TARGET_BRANCH} --single-branch ${CIRCLE_REPOSITORY_URL} deploy
            cd deploy
            git rm -rf .
            cp -r ../book/* .
      - run:
          name: Deploy release
          command: sh ./.circleci/deploy.sh $TARGET_BRANCH $CIRCLE_SHA1
